### ISSUE TITLE
save_session_data

### ISSUE THREAD

**Issue by siamakhaz** [ethierlab/Motopya#10]
when i try to save the data of the session I get the error for creating the folder 
in main.py from line 185 - 193 you can replace it with ```os.makedirs(rat_dir, exist_ok=True)```
and check the permissions before starting the session in this case user wont loose any data

**Comment by siamakhaz** [comment]
@rudy-saal  also the 1_RatKnob_trial_table_20240813_002720.csv file content is just the headers of the CSV file nothing more

**Comment by rudy-saal** [comment]
@siamakhaz what kind of permissions need to be checked?

**Comment by rudy-saal** [comment]
main was still accessing the other file for results and not the running session class so the output was empty. The empty folder is resolved and the suggested line has been replaced.

The permission check has not been implemented yet.
[feature: output for session class working](https://github.com/ethierlab/Motopya/commit/82d12b829e1b1955ab784cfe6f934a8bb72c72ad)

**Comment by siamakhaz** [comment]
the write access to the folder to create the folder and the files there.

instead of all of this part
```
if not dir_exists:
        message = f'Creating new folder for animal parameters["ratID"]\n'
        try:
            dir_exists = True
            os.mkdir(rat_dir)
        except OSError:
            dir_exists = False
            message = 'Failed to create new folder in specified location'
            return False, message
```
you can simply use this 
``` os.makedirs(rat_dir, exist_ok=True)```

**Comment by rudy-saal** [comment]
@siamakhaz but if the script is what creates the folder wouldn't that mean that is has all the permissions?

**Comment by rudy-saal** [comment]
@siamakhaz 
If I run this at the beginning does that work? Or maybe I have to try to create a file too?
- >
try:
    os.makedirs(output_dir, exist_ok=True)
except PermissionError:
    print("Permission error")
    sys.exit()

**Comment by siamakhaz** [comment]
> @siamakhaz but if the script is what creates the folder wouldn't that mean that is has all the permissions?

Not necessarily we have to check sometimes python user does not have access to some specific folders and we have to make sure of that 
for example if we clone the project to the root folder this can happen cause the python user is not Root and we have to fix the permissions with ```chmod```  command

**Comment by siamakhaz** [comment]
> rk? Or maybe I have to

that might work but I think checking the permissions is a better way to do it.

To check the permissions of your Python working folder, you can use the following Python code:

```python
import os
import stat

# Get the path of the current working directory
working_directory = os.getcwd()

# Get the permissions of the directory
permissions = os.stat(working_directory).st_mode

# Convert the permissions to a human-readable format
readable_permissions = stat.filemode(permissions)

print(f"Permissions for {working_directory}: {readable_permissions}")
```

This code will output the permissions in a format similar to `drwxr-xr-x`, which represents the permissions for the directory.

- `d`: Directory
- `rwx`: Read, write, and execute permissions for the owner
- `r-x`: Read and execute permissions for the group
- `r-x`: Read and execute permissions for others

You can run this script in your Python environment to see the permissions of your current working directory.

**Comment by rudy-saal** [comment]
added permission verification (tested in separate folder)
[feature: check permissions before running](https://github.com/ethierlab/Motopya/commit/8ee1c29f7bd2a96a1ab4e308afa2ca6a87630975)
