### ISSUE TITLE
i got this error when i ran the latest 

### ISSUE THREAD

**Issue by siamakhaz** [ethierlab/Motopya#16]
i think i dont have the resource that you are using in my RP5 please modify the requirement check 

<img width="464" alt="image" src="https://github.com/user-attachments/assets/29662f74-742f-4a64-8b7a-c0c3be9789c1">

**Comment by rudy-saal** [comment]
fixed in commit : [docs: added ads1015 to requirements](https://github.com/ethierlab/Motopya/commit/f505562be95418c1aee8b90ffb578109c0848e19)
added ads1015 to requirements.txt
