### ISSUE TITLE
add try catchs for all the dependencies 

### ISSUE THREAD

**Issue by siamakhaz** [ethierlab/Motopya#7]
imagine we running this code on a new device after 2 month we remember nothing so we had to have something to check and automatically install all the dependencies for us

**Comment by siamakhaz** [comment]
this function should run before main or at the beginning of the main

**Comment by rudy-saal** [comment]
added a try catch that checks if every import in requirements.txt is installed.

[feature: check for requirements before running main](https://github.com/ethierlab/Motopya/commit/5b8167a14a3a19706ff33b5dac7c5d6234f59706)

**Comment by rudy-saal** [comment]
added auto-install (the function takes a boolean that determines if it should install or not)

commit: [feature: auto-install feature](https://github.com/ethierlab/Motopya/commit/3f486b78448b7affffbea99e2b286d1ad7b5b223)
