### ISSUE TITLE
HitWindows Timing Bug

### ISSUE THREAD

**Issue by siamakhaz** [ethierlab/Motopya#8]
with this set of config 
the code only record 1 sec instead of 2 sec for hitWindow

iniThreshold,1
iniBaseline,1
minDuration,30
hitWindow,2
hitThresh,40
hitThreshAdapt,False
hitThreshMin,
hitThreshMax,
leverGain,1
forceDrop,2
maxTrials,100
holdTime,1
holdTimeAdapt,False
holdTimeMin,
holdTimeMax,
saveFolder,
ratID,1

**Comment by siamakhaz** [comment]
I can add even after passing the threshold the code always shows "FAIL"

**Comment by rudy-saal** [comment]
I pushed a fix for the failure: the peak value was not being reset at the right spot.

For the recording, I am assuming that it was failing and going straight to the post trial, which is set to 1 second long, so the recording is the length of the trial until success or failure + the length of the post trial duration, which record a little longer afterwards. 

In you case it only recorded the 1 second after the continuous failure
