### ISSUE TITLE
hit Thresh and Hold time  adaptive bug 

### ISSUE THREAD

**Issue by siamakhaz** [ethierlab/Motopya#9]
when I don't define the min and max for these parameters I encounter a report in the command line that says:
ValueError: could not convert string to float: '' in line 572 in gui.py

**Comment by rudy-saal** [comment]
Fixed with [hotfix: empty adapt fix](https://github.com/ethierlab/Motopya/commit/325745921f23733c7516675170198a3ed7c44fdf)

also added utils file for certain functions
